name: ML Model CI/CD with MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas matplotlib scikit-learn mlflow

    - name: Run Training Script
      run: |
        python your_script.py

    - name: Log Model to MLflow
      run: |
        mlflow run . --entry-point your_script.py

    - name: Print Metrics
      run: |
        echo "Model accuracy: $(cat accuracy.txt)"
        echo "Confusion matrix: $(cat confusion_matrix.txt)"

    - name: Upload Logs
      uses: actions/upload-artifact@v3
      with:
        name: ml-logs
        path: |
          accuracy.txt
          confusion_matrix.txt
